### ISSUE TITLE
Terminology alignment with PCRE

### ISSUE THREAD

**Issue by o314** [tree-sitter/tree-sitter-regex#2]
According to https://github.com/tree-sitter/tree-sitter-regex/blob/master/corpus/main.txt ,
current terminology of Tree sitter is aligned with [PCRE pattern](https://www.pcre.org/original/doc/html/pcrepattern.html) for

- sequence
- assertion
- character classes
- quantifier

But not with

- alternative where disjunction is used.

i suggest to keep pcre naming and use alternative instead of disjunction.

Abbreviations come easy too.  
Consider `(rep (alt 0 1) 1 n)` for binary integer.  
Very simple to read, simple to write and to understand.

Those ones could also help to get a leaner ast

- sequence (seq)
- alternative (alt)
- repetition (rep)
- optional (opt)
- ...

**Comment by maxbrunsfeld** [comment]
In general, I've avoided abbreviations in node type names. I'd prefer to use whole words, for the most part.

I'm ok with renaming `disjunction` to `alternation`. Want to open a PR?
