### ISSUE TITLE
Upload Rust crate to crates.io

### ISSUE THREAD

**Issue by langston-barrett** [tree-sitter/tree-sitter-regex#20]
I'd like to use this crate as a dependency for a crate that I would like to upload to crates.io. Any chance this crate could be released to crates.io?

**Comment by langston-barrett** [comment]
Hi, I don't actually see a version on crates.io yet. Am I missing something? https://crates.io/search?q=tree-crasher-regex

**Comment by the-mikedavis** [comment]
I see it here https://crates.io/crates/tree-sitter-regex

**Comment by langston-barrett** [comment]
Huh, It's now also showing up for me in the search. Weird. Thanks!
