### ISSUE TITLE
Decimal backreference escapes

### ISSUE THREAD

**Issue by th-we** [tree-sitter/tree-sitter-regex#3]
I tried to fix this problem:

    $ echo '(a)\1' > /tmp/decimal-backreference.txt
    $ node_modules/.bin/tree-sitter parse /tmp/decimal-backreference.txt 
    (pattern [0, 0] - [1, 0]
      (term [0, 0] - [0, 3]
        (anonymous_capturing_group [0, 0] - [0, 3]
          (pattern [0, 1] - [0, 2]
            (term [0, 1] - [0, 2]
              (pattern_character [0, 1] - [0, 2])))))
      (ERROR [0, 3] - [0, 5]
        (ERROR [0, 3] - [0, 5])))
    /tmp/decimal-backreference.txt	0 ms	(ERROR [0, 3] - [0, 5])

... in these two branches of mine:

https://github.com/th-we/tree-sitter-regex/commit/4d1076d670674f8f463a6b40b45f3ccfae9c7885
https://github.com/th-we/tree-sitter-regex/commit/135e904a7506915f2f8758941abce11bddfeb78e

Why is that?  (As a general question: What's the best place to get help with problems writing tree-sitter grammars?)

**Comment by the-mikedavis** [comment]
I think this is actually quite complicated to parse. Whether a decimal escape is a backreference depends on the number of anonymous capture groups preceeding the decimal escape, and the number of the decimal escape: in the example `(a)\1\2`, `\1` is a backreference but `\2` is a decimal escape, and in the example `(a)(b)\1\2`, both `\1` and `\2` are backreferences. I'm not a parser expert but I think LALR parsers might have a hard time describing a language like this.

I suspect once #9 is merged, though, it would be possible to write a query that could correctly distinguish the two, although it would be a bit hard-coded for each backreference:

```scheme
((anonymous_capturing_group)
 (decimal_escape) @constant
 (#eq? @constant "\\1"))

((anonymous_capturing_group)
 (anonymous_capturing_group)
 (decimal_escape) @constant @_escape1
 (decimal_escape) @constant @_escape2
 (#eq? @_escape1 "\\1")
 (#eq? @_escape2 "\\2"))

; and so on...
```

To keep the grammar simple, I think it makes sense to compromise and always mark escaped decimals as `decimal_escape`s

(edit: fix typos digit=>decimal)
