### ISSUE TITLE
hang on 100% CPU usage when editing certain regex

### ISSUE THREAD

**Issue by litoj** [tree-sitter/tree-sitter-regex#30]
### Describe the bug

When trying to edit certain regexes, nvim started hanging on me with 100% CPU usage.

### To Reproduce

I've minified the regex to the minimum amount of characters needed to reproduce the bug. Originally, the escape key was there to match ansi sequences.

- [x.txt](https://github.com/user-attachments/files/16623319/x.txt)
- neovim with bash & regex parsers installed:

      :e /tmp/x.txt
      10lx

### Expected behavior

the closing parenthese gets deleted

### Syntax tree:

(added `x` to the empty group to remove one syntax error)
```scm
        (pattern ; [0, 9] - [0, 25]
          (alternation ; [0, 9] - [0, 25]
            (term ; [0, 9] - [0, 12]
              (anonymous_capturing_group ; [0, 9] - [0, 12]
                (pattern ; [0, 10] - [0, 11]
                  (term ; [0, 10] - [0, 11]
                    (pattern_character))))) ; [0, 10] - [0, 11]
            (term ; [0, 13] - [0, 25]
              (anonymous_capturing_group ; [0, 13] - [0, 25]
                (pattern ; [0, 14] - [0, 24]
                  (term ; [0, 14] - [0, 24]
                    (end_assertion) ; [0, 14] - [0, 15]
                    (ERROR) ; [0, 15] - [0, 16]
                    (pattern_character) ; [0, 16] - [0, 17]
                    (character_class ; [0, 17] - [0, 20]
                      (class_character)) ; [0, 18] - [0, 19]
                    (pattern_character) ; [0, 20] - [0, 21]
                    (pattern_character) ; [0, 21] - [0, 22]
                    (pattern_character) ; [0, 22] - [0, 23]
                    (pattern_character))))))) ; [0, 23] - [0, 24]
```

In terms of highlighting, the issue is that in bash the regex string can also contain bash variables and their syntax, but the parser doesn't detect that, so it tries to parse it as usual. But the freeze is the real issue.

**Comment by amaanq** [comment]
that's not enough to go off of, I can't tell if this is because of the bash parser or regex parser, and it'd be clearer if you:

1. Used the CLI to verify that the core lib or parser hangs
2. Clearly indicated the (row, col) edit (and for how many bytes) that causes the hang
2. Pasted your code as plaintext...

**Comment by litoj** [comment]
I don't know what (row,col) edit should be indicated, but the vim command says it is the 11th character. From the expected behaviour you can understand, that I was trying to remove the closing parenthese in the file. The textfile is plaintext and pasting it wouldn't make sense, since you wouldn't be able to copy it properly anyways, because the <kbd>Escape</kbd> keykode isn't a visible char. There are no multibyte characters, so I don't know what you mean by _"for how many bytes"_.

I will try to use the cli to provide additional findings.
