### ISSUE TITLE
Document what flavor of regular expressions this grammar supports

### ISSUE THREAD

**Issue by keidax** [tree-sitter/tree-sitter-regex#41]
After quickly scanning the rules, I'm guessing this is meant to parse PCRE2 or ECMAScript regular expressions. It would be helpful if the project explained this explicitly.

**Comment by amaanq** [comment]
It's a somewhat "general" regex parser, and doesn't strictly adhere to one regex flavor. There's support for PCRE2, ECMAScript, and POSIX regexes.

**Comment by amaanq** [comment]
I've just updated the docs w/ this info
